config/routes.rb
Rails.application.routes.draw do
  resources :matches, only: [:read, :index]
  resources :comments
  resources :events
  devise_for :users
  get 'static_pages/home'
  root to: 'static_pages#home'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :comments
end

app/models/match.rb
class Match < ActiveRecord::Base

    def self.results
        today = Time.new.to_datetime.prev_day.strftime("%Y/%m/%d")
        data = HTTParty.get "http://api.sportradar.us/soccer-t2/sa/matches/2015/09/20/boxscore.xml?api_key=xrffgfeu9894j8pds927wcy4"
    end
    def self.resultsb
        today = Time.new.to_datetime.prev_day.strftime("%Y/%m/%d")
        data = HTTParty.get "http://api.sportradar.us/soccer-t2/na/matches/#{today}/boxscore.xml?api_key=57x5unse7m3xq2mv4a549rze"
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_permitted_parameters, if: :devise_controller?
  protected
  def configure_devise_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [ :index, :show ]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.order("created_at DESC").find(params[:id])
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to event_path(@comment.event_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to event_path(@comment.event_id), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @comments = @event.comments.all
    @comment = @event.comments.build
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :content)
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.results
    @nmatches = Match.resultsb
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:name, :body, :match_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
  base_title = "FANSCO"
  if page_title.empty?
    base_title
  else
    "#{base_title} | #{page_title}"
  end
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
  def get_url_label_for_match(match)
    "#{match['home']['name']} (#{match['home']['country_code']}) -- #{match['home']['score']} : #{match['away']['score']} -- #{match['away']['name']}(#{match['away']['country_code']})"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @comment.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h4>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="comment_form">
  <div class="form-group">
    <%= f.label :comment, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :body, class: "form-control" %>
    </div>
  </div>
  <%= f.hidden_field :event_id %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="page-header">
  <h1>Editing comment
    <div class = "link">
      <%= link_to events_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
      <% end %>
    </div>
  </h1>
  <br/>
</div>
<%= render 'form' %>

app/views/comments/index.html.erb
<div class="page-header">
  <%= link_to new_comment_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Comment
  <% end %>
  <h1>Listing comments</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>User name</th>
        <th>Body</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @comments) do |comment| %>
        <td><%= comment.body %></td>
        <td><%= comment.event_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/comments/new.html.erb
<div class="page-header">
  <%= link_to comments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New comment</h1>
</div>

<%= render 'form' %>

app/views/comments/show.html.erb
<div class="page-header">
  <%= link_to events_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_comment_path(@comment), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
</div>

app/views/events/_form.html.erb
<%= form_for(@event, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @event.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h4>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :content, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="page-header">
  <%= link_to events_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @event, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing event</h1>
</div>
<%= render 'form' %>

app/views/events/index.html.erb
<div class="page-header">
  <h1>Tennis Matches Forum
  <% if user_signed_in? %>
  <div class = "link">
    <%= link_to new_event_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Event
    <% end %>
    <% end %>
  </div>
  </h1>
</div>
<div class="col-md-5 col-md-offset-3">
<div class="table-responsive" id="tennis-table">
  <table class="table table-striped table-bordered table-hover" >
      <tr><td><h2>Choose Match</h2></td></tr>
      <%= content_tag_for(:tbody, @events) do |event| %>
          <tr><td><%= event.name %></td></tr>
          <tr><td><%= link_to event.content, event %></td></tr>
         <tr><td></td></tr>
      <% end %>
  </table>
</div>
</div>

app/views/events/new.html.erb
<div class="page-header">
<h1>New event
 <div class = "link">
  <%= link_to events_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  </div>
  </h1>
</div>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="page-header">
  <h1><%= @event.name %>
    <div class="link">
      <%= link_to events_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back to Events
      <% end %>
    </div>
  </h1>
</div>

<div class="event_content">
  <h2><%= @event.content %></h2>
</div>
<div class="comment-form">
  <h2>Comments</h2>
  <br/>
  <div class="col-md-8 col-md-offset-2">
    <% @comments.order(created_at: :desc).each do |comment| %>
      <div class="comment">
        <div class="comment-header">
          <strong><%= comment.user.full_name %></strong>
          <div class="timestamp">
          <i>created</i>
          <strong><%= comment.created_at.strftime("%b %d, %l:%M %p") %></strong>
          </div>
          <br />
        </div>
      <div class="comment-body">
        <p><%= comment.body %></p>
        <% if user_signed_in? %>
        <% if comment.user.id === current_user.id then %>
        <p><i><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Edit', edit_comment_path(comment)  %></i></p>
        <% end %>
        <% end %>
      </div>
      </div>
      <% end %>
    <% if user_signed_in? %>
      <%= render 'comments/form' %>
    <% end %>
  </div>
</div>

app/views/events/test.html.erb
<%= @index_number %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title><%= full_title(yield(:title)) %></title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--<% if user_signed_in? %>
   Signed in as <%=current_user.email %>. Not you?
  <% end %>-->
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "FANSCO", root_path, id: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Tennis", events_path %></li>
          <li><%= link_to "Soccer", matches_path %></li>
          <li><% if user_signed_in? %>
          <%= link_to 'Sign out', destroy_user_session_path, data: {method: :delete} %>
          <% else %>
          <%= link_to "Sign in", new_user_session_path %>
          <% end %>
          </li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/matches/_form.html.erb
<%= form_for(@match, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @match.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h4>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :body, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :match_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :match_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/matches/edit.html.erb
<div class="page-header">
  <%= link_to matches_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @match, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing match</h1>
</div>

<%= render 'form' %>

app/views/matches/index.html.erb
<div class="match-page">
<div class="page-header">
  <h1>Today's Matches</h1>
</div>

<div class="soccer-table">
<h2>South America</h2>
<div class="table-responsive table-striped">
<% if @matches["boxscore"]["matches"] == nil %>
<table class="table table-striped table-bordered table-hover">
    <tbody>
      <tr><td><h3>No Matches in South America for today</h3></td></tr>
    </tbody>
  </table>
  <% else %>
 <% @matches["boxscore"]["matches"]["match"].each do |match| %>
  <table class="table table-striped table-bordered table-hover">
    <tbody>
      <tr><td><h3><%= match["tournament_group"]["name"] %>--<%=match["category"]["name"] %>--<%=match["home"]["country"] %></h3></td></tr>
      <tr><td><h3><%= get_url_label_for_match(match) %></h3></td></tr>
    </tbody>
  </table>
 <% end %>
 <% end %>
</div>
<br/>
<h2>North America</h2>
<div class="table-responsive table-striped">
<% if @nmatches["boxscore"]["matches"] == nil %>
<table class="table table-striped table-bordered table-hover">
    <tbody>
      <tr><td><h3>No Matches in North America for today</h3></td></tr>
    </tbody>
  </table>
  <% else %>
 <% @nmatches["boxscore"]["matches"]["match"].each do |match| %>
  <table class="table table-striped table-bordered table-hover">
    <tbody>
      <tr><td><h3><%= match["tournament_group"]["name"] %>--<%=match["category"]["name"] %>--<%=match["home"]["country"] %></h3></td></tr>
      <tr><td><h3><%= get_url_label_for_match(match) %></h3></td></tr>
    </tbody>
  </table>
 <% end %>
 <% end %>
</div>
</div>

app/views/matches/new.html.erb
<div class="page-header">
  <%= link_to matches_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New match</h1>
</div>

<%= render 'form' %>

app/views/matches/show.html.erb
<div class="page-header">
  <%= link_to matches_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_match_path(@match), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show match</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @match.name %></dd>

  <dt>Body:</dt>
  <dd><%= @match.body %></dd>

  <dt>Match:</dt>
  <dd><%= @match.match_id %></dd>

</dl>

app/views/static_pages/home.html.erb
<div class="text-center jumbotron">
  <h1>Welcome to FANSCO</h1>
  <h2>Fans Unite!</h2>
  <h2>Get access to thousands of tennis and soccer mathces</h2>
  <div class="btn btn-success" role="button"><%= link_to "Create New Account", new_user_registration_path %></div>
  <br/>
</div>